version: '3.1'
services:

  db:
    image: postgres
    container_name: postgres_api
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stripe-exaple
